// <auto-generated />
namespace WpfGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class TabletblPictures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabletblPictures));
        
        string IMigrationMetadata.Id
        {
            get { return "201910141106534_Table tblPictures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
